export const imageCategories = [
    {
        id: 'none',
        name: 'None',
        description: '',
        imageUrl: 'https://image.pollinations.ai/prompt/no prompt?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: 'photorealistic',
        name: 'Photorealistic',
        description: 'photorealistic style, high detail, ultra-realistic lighting, 4k quality, professional photography',
        imageUrl: 'https://image.pollinations.ai/prompt/A%20photorealistic%20image%2C%20high%20detail%2C%204k%2C%20professional%20photography?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: 'art',
        name: 'Art',
        description: 'vibrant abstract expressionism style, bold colors, rich textures, dynamic composition',
        imageUrl: 'https://image.pollinations.ai/prompt/A%20vibrant%20and%20abstract%20piece%20of%20art%2C%20full%20of%20color%20and%20texture%2C%20style%20of%20expressionism?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: 'cyberpunk',
        name: 'Cyberpunk',
        description: 'futuristic dystopian style, neon lighting, rain-soaked atmosphere, Blade Runner aesthetic',
        imageUrl: 'https://image.pollinations.ai/prompt/A%20high-tech%2C%20dystopian%20cityscape%20at%20night%2C%20drenched%20in%20neon%20light%20and%20falling%20rain%2C%20Blade%20Runner%20aesthetic?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: 'anime',
        name: 'Anime',
        description: 'anime style with hand-drawn feel, cel-shading, warm nostalgic atmosphere, Studio Ghibli-inspired',
        imageUrl: 'https://image.pollinations.ai/prompt/A%20vibrant%20anime%20scene%20in%20the%20style%20of%20Studio%20Ghibli%2C%20beautiful%20hand-drawn%20background%2C%20cel-shaded%20characters%2C%20warm%20and%20nostalgic?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: '3d_model',
        name: '3D Model',
        description: '3D model style, soft playful lighting, detailed textures, modern animated film aesthetic',
        imageUrl: 'https://image.pollinations.ai/prompt/A%20charming%203D%20character%20model%20with%20soft%2C%20playful%20lighting%2C%20highly%20detailed%20textures%2C%20in%20the%20style%20of%20a%20modern%20animated%20film?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: 'fantasy',
        name: 'Fantasy',
        description: 'epic fantasy style, dramatic lighting, ancient magic ambiance, cinematic scale',
        imageUrl: 'https://image.pollinations.ai/prompt/Epic%20fantasy%20concept%20art%20of%20a%20mythical%20landscape%2C%20with%20dramatic%20lighting%2C%20towering%20castles%2C%20and%20a%20sense%20of%20ancient%20magic?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: 'illustrations',
        name: 'Illustrations',
        description: 'botanical illustration style, intricate linework, vintage aesthetic, fine detail on neutral background',
        imageUrl: 'https://image.pollinations.ai/prompt/A%20detailed%20botanical%20illustration%20with%20intricate%20linework%2C%20vintage%20style%2C%20on%20an%20off-white%20background?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: 'line_art',
        name: 'Line Art',
        description: 'minimalist line art style, clean one-line drawing, elegant simplicity on white background',
        imageUrl: 'https://image.pollinations.ai/prompt/A%20minimalist%20one-line%20drawing%20on%20a%20clean%20white%20background%2C%20elegant%20and%20simple%2C%20black%20ink?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: 'papercraft',
        name: 'Papercraft',
        description: 'papercraft diorama style, layered paper depth, soft studio lighting, handcrafted look',
        imageUrl: 'https://image.pollinations.ai/prompt/An%20intricate%20diorama%20made%20of%20layered%20paper%20%28papercraft%29%2C%20soft%20studio%20lighting%2C%20showing%20depth%20and%20detail?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: 'pen_ink',
        name: 'Pen & Ink',
        description: 'pen and ink style, high contrast black and white, dramatic lighting, film noir vibe',
        imageUrl: 'https://image.pollinations.ai/prompt/A%20sharp%2C%20high-contrast%20black%20and%20white%20portrait%2C%20cinematic%2C%20dramatic%20lighting%2C%20film%20noir%20style?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: 'vintage_photo',
        name: 'Vintage Photo',
        description: 'vintage photograph style, warm Kodachrome tones, soft focus, visible film grain',
        imageUrl: 'https://image.pollinations.ai/prompt/A%20nostalgic%20photograph%20from%20the%201970s%2C%20with%20warm%20Kodachrome%20colors%2C%20soft%20focus%2C%20and%20visible%20film%20grain?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: 'blueprint',
        name: 'Blueprint',
        description: 'technical blueprint style, schematic white lines on blue background, grid annotations',
        imageUrl: 'https://image.pollinations.ai/prompt/A%20detailed%20technical%20blueprint%20of%20a%20futuristic%20vehicle%20on%20a%20blue%20background%2C%20with%20white%20lines%2C%20grid%20annotations%2C%20and%20schematic%20details?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: 'noir',
        name: 'Film Noir',
        description: 'film noir style, black and white, harsh lighting, deep shadows, 1940s mystery aesthetic',
        imageUrl: 'https://image.pollinations.ai/prompt/Cinematic%20black%20and%20white%20style%20with%20harsh%20lighting%2C%20deep%20shadows%2C%201940s%20mystery%20aesthetic?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: 'isometric',
        name: 'Isometric Art',
        description: 'isometric style, clean flat 3D look, modern infographic aesthetic',
        imageUrl: 'https://image.pollinations.ai/prompt/Clean%20isometric%20view%20of%20buildings%20or%20environments%2C%20modern%20infographic%20style%2C%20flat%203D%20look?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: 'pixel_art',
        name: 'Pixel Art',
        description: 'pixel art style, retro 8-bit/16-bit aesthetic, bright blocks, simple shading',
        imageUrl: 'https://image.pollinations.ai/prompt/Retro%20pixel-style%20game%20art%2C%208-bit%20or%2016-bit%20aesthetic%2C%20bright%20blocks%20and%20simple%20shading?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: 'steampunk',
        name: 'Steampunk',
        description: 'steampunk style, industrial gears, brass machinery, Victorian sci-fi fusion',
        imageUrl: 'https://image.pollinations.ai/prompt/Industrial%20revolution%20meets%20sci-fi%3B%20gears%2C%20brass%2C%20steam-powered%20machinery%2C%20Victorian%20flair?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: 'minimalist',
        name: 'Minimalist',
        description: 'minimalist style, simple compositions, limited palette, ample negative space, zen design',
        imageUrl: 'https://image.pollinations.ai/prompt/Simple%2C%20clean%20compositions%20with%20limited%20color%20palettes%2C%20lots%20of%20negative%20space%2C%20zen%20design?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: 'concept_art',
        name: 'Concept Art',
        description: 'concept art style, rough cinematic feel, epic scale, matte painting vibe',
        imageUrl: 'https://image.pollinations.ai/prompt/Rough%20cinematic%20concept%20art%2C%20epic%20scale%2C%20matte%20painting%20feel%2C%20pre-visualization%20style?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: 'low_poly',
        name: 'Low Poly',
        description: 'low poly 3D style, stylized geometric shapes, minimal textures, colorful',
        imageUrl: 'https://image.pollinations.ai/prompt/Stylized%203D%20graphics%20with%20low%20polygon%20count%2C%20colorful%2C%20geometric%2C%20minimal%20textures?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: 'watercolor',
        name: 'Watercolor',
        description: 'watercolor painting style, soft loose brushstrokes, bleeding colors, textured paper feel',
        imageUrl: 'https://image.pollinations.ai/prompt/Soft%20watercolor%20painting%2C%20loose%20brushstrokes%2C%20bleeding%20colors%2C%20paper%20texture?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: 'sketch',
        name: 'Pencil Sketch',
        description: 'pencil sketch style, hand-drawn outlines, cross-hatching shading, paper texture',
        imageUrl: 'https://image.pollinations.ai/prompt/Hand-drawn%20pencil%20sketch%20with%20cross-hatching%2C%20raw%20outlines%2C%20shading%20and%20paper%20texture?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: 'surreal',
        name: 'Surrealism',
        description: 'surreal style, dream-like visuals, absurd paradoxical elements, Dalí influence',
        imageUrl: 'https://image.pollinations.ai/prompt/Dream-like%2C%20absurd%2C%20impossible%20visuals%2C%20Salvador%20Dal%C3%AD%20influence%2C%20visual%20paradoxes?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: 'futuristic_ui',
        name: 'Futuristic UI',
        description: 'futuristic UI style, sci-fi HUD panels, holographic overlays, neon data elements',
        imageUrl: 'https://image.pollinations.ai/prompt/Sci-fi%20UI%20panels%20and%20interfaces%2C%20HUDs%2C%20digital%20holograms%2C%20neon%20data%20overlays?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: 'product_mockup',
        name: 'Product Mockup',
        description: 'product mockup style, clean white background, realistic rendering, branding focus',
        imageUrl: 'https://image.pollinations.ai/prompt/Clean%20product-on-white%20background%20renders%2C%20packaging%20and%20branding%20visualization?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: 'neon_glow',
        name: 'Neon Glow',
        description: 'neon glow style, vibrant colors, dark background, synthwave aesthetic',
        imageUrl: 'https://image.pollinations.ai/prompt/Vibrant%20neon%20colors%2C%20dark%20backgrounds%2C%20glowing%20lights%2C%20synthwave%20aesthetic?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: 'flat_vector',
        name: 'Flat Vector',
        description: 'flat vector style, simple shapes, modern UI aesthetic, smooth curves',
        imageUrl: 'https://image.pollinations.ai/prompt/Simple%20flat%20illustrations%2C%20vector%20graphics%2C%20modern%20UI%20style%2C%20smooth%20curves?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: 'sci_fi_landscape',
        name: 'Sci-Fi Landscape',
        description: 'sci-fi landscape style, alien environments, glowing flora, futuristic structures, surreal vibe',
        imageUrl: 'https://image.pollinations.ai/prompt/Alien%20world%20with%20multiple%20moons%2C%20glowing%20flora%2C%20futuristic%20structures%2C%20surreal%20vibe?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: 'fashion_illustration',
        name: 'Fashion Illustration',
        description: 'fashion illustration style, stylized runway sketches, elongated poses, elegant brush lines',
        imageUrl: 'https://image.pollinations.ai/prompt/Stylized%20runway%20sketches%2C%20elongated%20poses%2C%20elegant%20brush%20lines%2C%20haute%20couture%20feel?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: 'retro_futurism',
        name: 'Retro Futurism',
        description: 'retro futurism style, 1950s/60s sci-fi aesthetic, pastel colors, chrome accents',
        imageUrl: 'https://image.pollinations.ai/prompt/Sci-fi%20inspired%20by%201950s/60s%20design%2C%20atomic%20age%2C%20flying%20cars%2C%20pastel%20colors%2C%20chrome%20tech?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: 'diorama',
        name: 'Mini Diorama',
        description: 'miniature diorama style, handcrafted miniature look, tilt-shift photographic effect',
        imageUrl: 'https://image.pollinations.ai/prompt/Miniature%20physical%20scenes%2C%20handcrafted%20look%2C%20tiny%20furniture%2C%20tilt-shift%20lens%20effect?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: 'ui_wireframe',
        name: 'UI Wireframe',
        description: 'wireframe style, lo-fi grayscale schematic layout, UX design focus',
        imageUrl: 'https://image.pollinations.ai/prompt/Lo-fi%20grayscale%20wireframes%20for%20apps%20or%20websites%2C%20UX%20design%20layout%2C%20schematic%20feel?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: 'blue_hour',
        name: 'Blue Hour',
        description: 'blue hour photography style, twilight tones, deep blue gradients, cinematic calm mood',
        imageUrl: 'https://image.pollinations.ai/prompt/Photography%20at%20twilight%2C%20deep%20blue%20skies%2C%20soft%20gradients%2C%20cinematic%20calm%20mood?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: 'logo_designer',
        name: 'Logo Designer',
        description: 'logo design style, minimal vector lines, flat aesthetic, branding-ready',
        imageUrl: 'https://image.pollinations.ai/prompt/Modern%20minimal%20logo%20design%2C%20clean%20vector%20lines%2C%20flat%20style%2C%20branding-ready?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: 'branding_mockup',
        name: 'Branding Mockup',
        description: 'branding mockup style, professional stationery layout, premium presentation',
        imageUrl: 'https://image.pollinations.ai/prompt/Professional%20branding%20presentation%20mockup%2C%20business%20card%20and%20stationery%2C%20premium%20style?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: 'typography_poster',
        name: 'Typography Poster',
        description: 'typographic poster style, bold modern fonts, Swiss design layout, graphic impact',
        imageUrl: 'https://image.pollinations.ai/prompt/Bold%20modern%20typographic%20poster%2C%20graphic%20design%20layout%2C%20Swiss%20style?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: 'icon_set',
        name: 'Icon Set',
        description: 'icon set style, flat vector icons, consistent line weight, UI-friendly',
        imageUrl: 'https://image.pollinations.ai/prompt/Flat%20vector%20icon%20pack%2C%20consistent%20line%20weight%2C%20UI-friendly%20design?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: 'mockup_device',
        name: 'Device Mockup',
        description: 'device mockup style, clean presentations with mobile and laptop screens, realistic rendering',
        imageUrl: 'https://image.pollinations.ai/prompt/Modern%20device%20mockups%20with%20mobile%20and%20laptop%20screens%2C%20clean%20presentation%20for%20UI%20demos?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: 'infographic',
        name: 'Infographic Design',
        description: 'infographic style, creative data visualization, flat style charts and icons',
        imageUrl: 'https://image.pollinations.ai/prompt/Creative%20data%20visualization%20infographic%2C%20flat%20style%20charts%20and%20icons?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: 'poster_design',
        name: 'Poster Design',
        description: 'poster design style, eye-catching layouts, bold typography, campaign visuals',
        imageUrl: 'https://image.pollinations.ai/prompt/Creative%20poster%20design%20for%20events%20or%20campaigns%2C%20eye-catching%20layout%20and%20typography?enhance=true&width=512&height=512&nologo=true',
    }
];