export const imageCategories = [
    {
        id: 'none',
        name: 'None',
        description: '',
        imageUrl: 'https://image.pollinations.ai/prompt/no prompt?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: 'photorealistic',
        name: 'Photorealistic',
        description: 'A photorealistic, highly detailed, 4k professional photograph with ultra-realistic lighting of ',
        imageUrl: 'https://image.pollinations.ai/prompt/A%20photorealistic%20image%2C%20high%20detail%2C%204k%2C%20professional%20photography?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: 'art',
        name: 'Art',
        description: 'An abstract expressionist painting with bold colors, rich textures, and a dynamic composition, depicting ',
        imageUrl: 'https://image.pollinations.ai/prompt/A%20vibrant%20and%20abstract%20piece%20of%20art%2C%20full%20of%20color%20and%20texture%2C%20style%20of%20expressionism?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: 'cyberpunk',
        name: 'Cyberpunk',
        description: 'A futuristic, dystopian cyberpunk scene in the style of Blade Runner, with neon lighting and a rain-soaked atmosphere, showing ',
        imageUrl: 'https://image.pollinations.ai/prompt/A%20high-tech%2C%20dystopian%20cityscape%20at%20night%2C%20drenched%20in%20neon%20light%20and%20falling%20rain%2C%20Blade%20Runner%20aesthetic?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: 'anime',
        name: 'Anime',
        description: 'A vibrant anime scene in the style of Studio Ghibli, with a hand-drawn feel, cel-shading, and a warm, nostalgic atmosphere, featuring ',
        imageUrl: 'https://image.pollinations.ai/prompt/A%20vibrant%20anime%20scene%20in%20the%20style%20of%20Studio%20Ghibli%2C%20beautiful%20hand-drawn%20background%2C%20cel-shaded%20characters%2C%20warm%20and%20nostalgic?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: '3d_model',
        name: '3D Model',
        description: 'A charming 3D model in the style of a modern animated film, with soft, playful lighting and highly detailed textures, of ',
        imageUrl: 'https://image.pollinations.ai/prompt/A%20charming%203D%20character%20model%20with%20soft%2C%20playful%20lighting%2C%20highly%20detailed%20textures%2C%20in%20the%20style%20of%20a%20modern%20animated%20film?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: 'fantasy',
        name: 'Fantasy',
        description: 'Epic fantasy concept art with dramatic lighting, a cinematic scale, and an ambiance of ancient magic, of ',
        imageUrl: 'https://image.pollinations.ai/prompt/Epic%20fantasy%20concept%20art%20of%20a%20mythical%20landscape%2C%20with%20dramatic%20lighting%2C%20towering%20castles%2C%20and%20a%20sense%20of%20ancient%20magic?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: 'illustrations',
        name: 'Illustrations',
        description: 'A detailed botanical illustration with intricate linework and a vintage style, on an off-white background, of ',
        imageUrl: 'https://image.pollinations.ai/prompt/A%20detailed%20botanical%20illustration%20with%20intricate%20linework%2C%20vintage%20style%2C%20on%20an%20off-white%20background?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: 'line_art',
        name: 'Line Art',
        description: 'A minimalist and elegant one-line drawing in black ink on a clean white background, of ',
        imageUrl: 'https://image.pollinations.ai/prompt/A%20minimalist%20one-line%20drawing%20on%20a%20clean%20white%20background%2C%20elegant%20and%20simple%2C%20black%20ink?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: 'papercraft',
        name: 'Papercraft',
        description: 'An intricate diorama made of layered paper (papercraft), with soft studio lighting showing depth and detail, of ',
        imageUrl: 'https://image.pollinations.ai/prompt/An%20intricate%20diorama%20made%20of%20layered%20paper%20%28papercraft%29%2C%20soft%20studio%20lighting%2C%20showing%20depth%20and%20detail?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: 'pen_ink',
        name: 'Pen & Ink',
        description: 'A sharp, high-contrast black and white pen and ink drawing with dramatic, cinematic lighting in a film noir style, of ',
        imageUrl: 'https://image.pollinations.ai/prompt/A%20sharp%2C%20high-contrast%20black%20and%20white%20portrait%2C%20cinematic%2C%20dramatic%20lighting%2C%20film%20noir%20style?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: 'vintage_photo',
        name: 'Vintage Photo',
        description: 'A nostalgic vintage photograph from the 1970s, with warm Kodachrome colors, soft focus, and visible film grain, of ',
        imageUrl: 'https://image.pollinations.ai/prompt/A%20nostalgic%20photograph%20from%20the%201970s%2C%20with%20warm%20Kodachrome%20colors%2C%20soft%20focus%2C%20and%20visible%20film%20grain?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: 'blueprint',
        name: 'Blueprint',
        description: 'A detailed technical blueprint on a blue background, with white lines, grid annotations, and schematic details, of ',
        imageUrl: 'https://image.pollinations.ai/prompt/A%20detailed%20technical%20blueprint%20of%20a%20futuristic%20vehicle%20on%20a%20blue%20background%2C%20with%20white%20lines%2C%20grid%20annotations%2C%20and%20schematic%20details?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: 'noir',
        name: 'Film Noir',
        description: 'A cinematic black and white film noir style image with harsh lighting, deep shadows, and a 1940s mystery aesthetic, of ',
        imageUrl: 'https://image.pollinations.ai/prompt/Cinematic%20black%20and%20white%20style%20with%20harsh%20lighting%2C%20deep%20shadows%2C%201940s%20mystery%20aesthetic?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: 'isometric',
        name: 'Isometric Art',
        description: 'A clean isometric view with a modern infographic style and a flat 3D look, of ',
        imageUrl: 'https://image.pollinations.ai/prompt/Clean%20isometric%20view%20of%20buildings%20or%20environments%2C%20modern%20infographic%20style%2C%20flat%203D%20look?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: 'pixel_art',
        name: 'Pixel Art',
        description: 'Retro 8-bit/16-bit pixel art with bright blocky colors and simple shading, of ',
        imageUrl: 'https://image.pollinations.ai/prompt/Retro%20pixel-style%20game%20art%2C%208-bit%20or%2016-bit%20aesthetic%2C%20bright%20blocks%20and%20simple%20shading?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: 'steampunk',
        name: 'Steampunk',
        description: 'A steampunk-style image where the industrial revolution meets sci-fi, with gears, brass, steam-powered machinery, and Victorian flair, showing ',
        imageUrl: 'https://image.pollinations.ai/prompt/Industrial%20revolution%20meets%20sci-fi%3B%20gears%2C%20brass%2C%20steam-powered%20machinery%2C%20Victorian%20flair?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: 'minimalist',
        name: 'Minimalist',
        description: 'A minimalist zen design with a simple composition, a limited color palette, and lots of negative space, of ',
        imageUrl: 'https://image.pollinations.ai/prompt/Simple%2C%20clean%20compositions%20with%20limited%20color%20palettes%2C%20lots%20of%20negative%20space%2C%20zen%20design?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: 'concept_art',
        name: 'Concept Art',
        description: 'Rough, cinematic concept art with an epic scale and a matte painting feel, for ',
        imageUrl: 'https://image.pollinations.ai/prompt/Rough%20cinematic%20concept%20art%2C%20epic%20scale%2C%20matte%20painting%20feel%2C%20pre-visualization%20style?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: 'low_poly',
        name: 'Low Poly',
        description: 'A stylized, colorful 3D graphic with a low polygon count and minimal textures, of ',
        imageUrl: 'https://image.pollinations.ai/prompt/Stylized%203D%20graphics%20with%20low%20polygon%20count%2C%20colorful%2C%20geometric%2C%20minimal%20textures?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: 'watercolor',
        name: 'Watercolor',
        description: 'A soft watercolor painting with loose brushstrokes, bleeding colors, and a paper texture, of ',
        imageUrl: 'https://image.pollinations.ai/prompt/Soft%20watercolor%20painting%2C%20loose%20brushstrokes%2C%20bleeding%20colors%2C%20paper%20texture?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: 'sketch',
        name: 'Pencil Sketch',
        description: 'A hand-drawn pencil sketch with cross-hatching, raw outlines, shading, and paper texture, of ',
        imageUrl: 'https://image.pollinations.ai/prompt/Hand-drawn%20pencil%20sketch%20with%20cross-hatching%2C%20raw%20outlines%2C%20shading%20and%20paper%20texture?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: 'surreal',
        name: 'Surrealism',
        description: 'A dream-like, surrealist image with absurd, impossible visuals and visual paradoxes, in the style of Salvador Dalí, of ',
        imageUrl: 'https://image.pollinations.ai/prompt/Dream-like%2C%20absurd%2C%20impossible%20visuals%2C%20Salvador%20Dal%C3%AD%20influence%2C%20visual%20paradoxes?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: 'futuristic_ui',
        name: 'Futuristic UI',
        description: 'A sci-fi UI panel or interface with HUDs, digital holograms, and neon data overlays, displaying ',
        imageUrl: 'https://image.pollinations.ai/prompt/Sci-fi%20UI%20panels%20and%20interfaces%2C%20HUDs%2C%20digital%20holograms%2C%20neon%20data%20overlays?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: 'product_mockup',
        name: 'Product Mockup',
        description: 'A clean product-on-white background render for packaging and branding visualization, of ',
        imageUrl: 'https://image.pollinations.ai/prompt/Clean%20product-on-white%20background%20renders%2C%20packaging%20and%20branding%20visualization?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: 'neon_glow',
        name: 'Neon Glow',
        description: 'A vibrant image with neon colors, a dark background, glowing lights, and a synthwave aesthetic, of ',
        imageUrl: 'https://image.pollinations.ai/prompt/Vibrant%20neon%20colors%2C%20dark%20backgrounds%2C%20glowing%20lights%2C%20synthwave%20aesthetic?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: 'flat_vector',
        name: 'Flat Vector',
        description: 'A simple flat vector illustration with a modern UI style and smooth curves, of ',
        imageUrl: 'https://image.pollinations.ai/prompt/Simple%20flat%20illustrations%2C%20vector%20graphics%2C%20modern%20UI%20style%2C%20smooth%20curves?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: 'sci_fi_landscape',
        name: 'Sci-Fi Landscape',
        description: 'A sci-fi landscape of an alien world with multiple moons, glowing flora, futuristic structures, and a surreal vibe, featuring ',
        imageUrl: 'https://image.pollinations.ai/prompt/Alien%20world%20with%20multiple%20moons%2C%20glowing%20flora%2C%20futuristic%20structures%2C%20surreal%20vibe?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: 'fashion_illustration',
        name: 'Fashion Illustration',
        description: 'A stylized runway sketch with elongated poses, elegant brush lines, and a haute couture feel, of ',
        imageUrl: 'https://image.pollinations.ai/prompt/Stylized%20runway%20sketches%2C%20elongated%20poses%2C%20elegant%20brush%20lines%2C%20haute%20couture%20feel?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: 'retro_futurism',
        name: 'Retro Futurism',
        description: 'Sci-fi art inspired by 1950s/60s retro-futurism and the atomic age, with flying cars, pastel colors, and chrome tech, showing ',
        imageUrl: 'https://image.pollinations.ai/prompt/Sci-fi%20inspired%20by%201950s/60s%20design%2C%20atomic%20age%2C%20flying%20cars%2C%20pastel%20colors%2C%20chrome%20tech?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: 'diorama',
        name: 'Mini Diorama',
        description: 'A miniature physical scene in a diorama, with a handcrafted look, tiny furniture, and a tilt-shift lens effect, of ',
        imageUrl: 'https://image.pollinations.ai/prompt/Miniature%20physical%20scenes%2C%20handcrafted%20look%2C%20tiny%20furniture%2C%20tilt-shift%20lens%20effect?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: 'ui_wireframe',
        name: 'UI Wireframe',
        description: 'A lo-fi grayscale wireframe for an app or website, with a UX design layout and schematic feel, for ',
        imageUrl: 'https://image.pollinations.ai/prompt/Lo-fi%20grayscale%20wireframes%20for%20apps%20or%20websites%2C%20UX%20design%20layout%2C%20schematic%20feel?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: 'blue_hour',
        name: 'Blue Hour',
        description: 'A cinematic and calm photograph taken at twilight during the blue hour, with deep blue skies and soft gradients, of ',
        imageUrl: 'https://image.pollinations.ai/prompt/Photography%20at%20twilight%2C%20deep%20blue%20skies%2C%20soft%20gradients%2C%20cinematic%20calm%20mood?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: 'logo_designer',
        name: 'Logo Designer',
        description: 'A modern, minimal, flat-style vector logo design with clean lines, ready for branding, for ',
        imageUrl: 'https://image.pollinations.ai/prompt/Modern%20minimal%20logo%20design%2C%20clean%20vector%20lines%2C%20flat%20style%2C%20branding-ready?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: 'branding_mockup',
        name: 'Branding Mockup',
        description: 'A premium, professional branding presentation mockup with a business card and stationery, for ',
        imageUrl: 'https://image.pollinations.ai/prompt/Professional%20branding%20presentation%20mockup%2C%20business%20card%20and%20stationery%2C%20premium%20style?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: 'typography_poster',
        name: 'Typography Poster',
        description: 'A bold, modern typographic poster with a graphic, Swiss-style layout, for ',
        imageUrl: 'https://image.pollinations.ai/prompt/Bold%20modern%20typographic%20poster%2C%20graphic%20design%20layout%2C%20Swiss%20style?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: 'icon_set',
        name: 'Icon Set',
        description: 'A flat vector icon pack with consistent line weight and a UI-friendly design, of ',
        imageUrl: 'https://image.pollinations.ai/prompt/Flat%20vector%20icon%20pack%2C%20consistent%20line%20weight%2C%20UI-friendly%20design?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: 'mockup_device',
        name: 'Device Mockup',
        description: 'A modern device mockup with a clean presentation for UI demos on mobile and laptop screens, showing ',
        imageUrl: 'https://image.pollinations.ai/prompt/Modern%20device%20mockups%20with%20mobile%20and%20laptop%20screens%2C%20clean%20presentation%20for%20UI%20demos?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: 'infographic',
        name: 'Infographic Design',
        description: 'A creative data visualization infographic with flat style charts and icons, about ',
        imageUrl: 'https://image.pollinations.ai/prompt/Creative%20data%20visualization%20infographic%2C%20flat%20style%20charts%20and%20icons?enhance=true&width=512&height=512&nologo=true',
    },
    {
        id: 'poster_design',
        name: 'Poster Design',
        description: 'A creative poster design for an event or campaign, with an eye-catching layout and typography, for ',
        imageUrl: 'https://image.pollinations.ai/prompt/Creative%20poster%20design%20for%20events%20or%20campaigns%2C%20eye-catching%20layout%20and%20typography?enhance=true&width=512&height=512&nologo=true',
    }
];
