// import { StyleSheet, Platform, Dimensions } from 'react-native';

// const { width } = Dimensions.get('window');

// export const styles = StyleSheet.create({
//   root: { flex: 1, backgroundColor: '#fff' },
//   chatHeader: { flexDirection: 'row', alignItems: 'center', padding: 12, borderBottomWidth: 1, borderColor: '#F1F5F9' },
//   headerIconButton: { padding: 8 },
//   chatTitle: { fontSize: 18, fontWeight: 'bold', color: '#1E293B', marginHorizontal: 12, flex: 1 },
//   userRow: { flexDirection: 'row', justifyContent: 'flex-end', margin: 8 },
//   userBubble: { backgroundColor: '#6366F1', padding: 12, borderRadius: 16, maxWidth: '80%' },
//   userText: { color: '#fff', fontSize: 16 },
//   aiRow: { flexDirection: 'row', margin: 8, alignItems: 'flex-end' },
//   avatar: { width: 32, height: 32, borderRadius: 16, backgroundColor: '#EEF2FF', justifyContent: 'center', alignItems: 'center', marginRight: 8 },
//   aiBubble: { backgroundColor: '#fff', padding: 12, borderRadius: 16, borderWidth: 1, borderColor: '#E2E8F0', maxWidth: '80%' },
//   errorBubble: { backgroundColor: '#FEF2F2', borderColor: '#FCA5A5' },
//   errorText: { color: '#B91C1C', fontSize: 16 },
//   time: { fontSize: 10, color: '#94A3B8', marginTop: 4, alignSelf: 'flex-end' },
//   errorTime: { color: '#FCA5A5' },
//   chatContent: { padding: 12, paddingBottom: 60 },
//   typingBubble: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', width: 60, height: 40 },
//   typingDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: '#94A3B8', margin: 3 },
//   inputRow: { flexDirection: 'row', padding: 8, backgroundColor: '#fff', borderTopWidth: 1, borderColor: '#E2E8F0' },
//   input: { flex: 1, padding: 12, backgroundColor: '#F1F5F9', borderRadius: 20, marginRight: 8, maxHeight: 100 },
//   sendBtn: { backgroundColor: '#6366F1', padding: 12, borderRadius: 20, justifyContent: 'center' },
//   sendDisabled: { backgroundColor: '#A5B4FC' },
//   listHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 16, borderBottomWidth: 1, borderColor: '#F1F5F9' },
//   listTitle: { fontSize: 18, fontWeight: 'bold', color: '#1E293B' },
//   searchContainer: { paddingHorizontal: 16, paddingVertical: 8, backgroundColor: '#fff' },
//   searchInput: { backgroundColor: '#F1F5F9', borderRadius: 20, paddingHorizontal: 12, height: 40, fontSize: 16, color: '#1E293B' },
//   threadsListContainer: { paddingVertical: 8 },
//   emptyContainer: { flex: 1, justifyContent: 'center', alignItems: 'center' },
//   emptyText: { marginTop: 8, fontSize: 16, color: '#64748B' },
//   threadCard: {
//     backgroundColor: '#fff',
//     marginHorizontal: 16,
//     marginVertical: 6,
//     borderRadius: 12,
//     ...Platform.select({
//       android: { elevation: 2 },
//       ios: { shadowColor: '#000', shadowOpacity: 0.1, shadowOffset: { width: 0, height: 1 }, shadowRadius: 2 },
//     }),
//   },
//   threadCardContent: { flexDirection: 'row', alignItems: 'center', padding: 12 },
//   threadIcon: { width: 40, height: 40, borderRadius: 20, backgroundColor: '#EEF2FF', justifyContent: 'center', alignItems: 'center', marginRight: 12 },
//   threadTextContainer: { flex: 1 },
//   threadTitle: { fontSize: 16, fontWeight: '600', color: '#1E293B' },
//   threadSnippet: { fontSize: 14, color: '#64748B', marginTop: 4 },
//   threadTime: { fontSize: 12, color: '#94A3B8', marginLeft: 8 },
//   settingsHeader: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 12, borderBottomWidth: 1, borderColor: '#F1F5F9', backgroundColor: '#fff' },
//   settingsTitle: { fontSize: 20, fontWeight: 'bold', color: '#1E293B', marginLeft: 16 },
//   settingsScrollView: { paddingVertical: 16, paddingHorizontal: 16 },
//   settingsCard: { backgroundColor: '#fff', borderRadius: 8, padding: 16, marginBottom: 16, ...Platform.select({ android: { elevation: 2 }, ios: { shadowColor: '#000', shadowOpacity: 0.1, shadowOffset: { width: 0, height: 1 }, shadowRadius: 2 } }) },
//   settingsCardHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 12 },
//   settingsCardIcon: { marginRight: 10 },
//   settingsCardTitle: { fontSize: 17, fontWeight: '600', color: '#1E293B' },
//   systemInstructionInput: { backgroundColor: '#F1F5F9', borderRadius: 6, padding: 12, minHeight: 100, textAlignVertical: 'top', color: '#1E293B', fontSize: 15, lineHeight: 20 },
//   settingsCharCount: { textAlign: 'right', fontSize: 12, color: '#64748B', marginTop: 8 },
//   modelOptionItem: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 14, paddingHorizontal: 12, backgroundColor: '#F8FAFC', borderRadius: 6, marginBottom: 8 },
//   modelOptionItemSelected: { backgroundColor: '#EEF2FF' },
//   modelOptionItemPressed: { backgroundColor: '#E0E7FF' },
//   modelOptionText: { fontSize: 15, color: '#334155' },
//   modelOptionTextSelected: { fontWeight: '600', color: '#1E293B' },
//   apiKeyInputContainer: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#F1F5F9', borderRadius: 6, paddingHorizontal: 12 },
//   apiKeyInput: { flex: 1, paddingVertical: 12, color: '#1E293B', fontSize: 15 },
//   showHideButton: { padding: 8, marginLeft: 8 },
//   settingsInfoTextSmall: { fontSize: 12, color: '#64748B', marginTop: 8 },
//   drawerContentContainer: { flex: 1, backgroundColor: '#fff' },
//   drawerHeaderContainer: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 20, paddingVertical: 20, borderBottomWidth: 1, borderBottomColor: '#F1F5F9' },
//   drawerLogo: { marginRight: 15 },
//   drawerHeaderText: { fontSize: 18, fontWeight: 'bold', color: '#1E293B' },
//   drawerSection: { marginTop: 10, marginBottom: 5 },
//   drawerItem: { flexDirection: 'row', alignItems: 'center', paddingVertical: 12, paddingHorizontal: 20, marginHorizontal: 12, borderRadius: 8, marginBottom: 2 },
//   drawerItemActive: { backgroundColor: '#EEF2FF' },
//   drawerItemPressed: { backgroundColor: '#E0E7FF' },
//   drawerIcon: { marginRight: 18, color: '#475569' },
//   drawerText: { fontSize: 15, color: '#334155', fontWeight: '500' },
//   drawerTextActive: { color: '#6366F1', fontWeight: '600' },
//   drawerSeparator: { height: 1, backgroundColor: '#F1F5F9', marginHorizontal: 20, marginVertical: 10 },
//   drawerFooterIcon: { marginRight: 18, color: '#64748B' },
//   drawerFooterText: { fontSize: 14, color: '#475569', fontWeight: 'normal' },
//   appVersionText: { textAlign: 'center', color: '#94A3B8', fontSize: 12, paddingVertical: 15, marginTop: 'auto' },
//   modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.3)', justifyContent: 'center', alignItems: 'center' },
//   modalTitle: { fontSize: 18, fontWeight: '600', color: '#1E293B', marginBottom: 16, textAlign: 'center' },
//   actionModal: { width: width * 0.85, backgroundColor: '#fff', borderRadius: 12, paddingVertical: 16, paddingHorizontal: 20 },
//   actionBtn: { flexDirection: 'row', alignItems: 'center', paddingVertical: 14, },
//   actionIcon: { marginRight: 12 },
//   actionText: { fontSize: 16, color: '#1E293B', },
//   deleteActionText: { color: '#DC2626' },
//   cancelActionBtn: { borderTopWidth: 1, borderColor: '#F1F5F9', marginTop: 8, paddingTop: 14 },
//   renameModal: { width: width * 0.85, backgroundColor: '#fff', borderRadius: 12, padding: 20 },
//   renameInput: { backgroundColor: '#F1F5F9', borderRadius: 6, paddingHorizontal: 12, paddingVertical: 10, fontSize: 16, color: '#1E293B', marginBottom: 20 },
//   renameBtns: { flexDirection: 'row', justifyContent: 'flex-end', marginTop: 12 },
//   modalButton: { paddingVertical: 10, paddingHorizontal: 20, borderRadius: 6, marginLeft: 10, minWidth: 80, alignItems: 'center' },
//   modalButtonPrimary: { backgroundColor: '#6366F1' },
//   modalButtonSecondary: { backgroundColor: '#E2E8F0' },
//   modalButtonText: { fontSize: 16, color: '#fff', fontWeight: '500' },
//   modalButtonTextSecondary: { color: '#334155' },
//   welcomeModal: { width: width * 0.9, backgroundColor: '#fff', borderRadius: 12, padding: 24 },
//   welcomeTitle: { fontSize: 20, fontWeight: '700', color: '#1E293B', textAlign: 'center', marginBottom: 12 },
//   welcomeText: { fontSize: 15, color: '#475569', textAlign: 'center', lineHeight: 22 },
// });